version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: auth-postgres
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass123
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U authuser -d authdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5001
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=authdb;Username=authuser;Password=authpass123"
      ConnectionStrings__IdentityConnection: "Host=postgres;Database=authdb;Username=authuser;Password=authpass123"
      IdentityServer__IssuerUri: "http://localhost:5001"
    ports:
      - "5001:5001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - auth-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local

networks:
  auth-network:
    driver: bridge